___

<a href='https://jupyter-notebook.readthedocs.io/en/stable/examples/Notebook/Running%20Code.html'> <img src='https://www.python.org/static/img/python-logo.png' /></a>
___

# NumPy Ejercicios

Ahora que hemos aprendido sobre NumPy, probemos los conocimientos. Comenzaremos con algunas tareas simples y luego se harán algunas preguntas más complicadas.

#### Importar NumPy como np

In [2]:
import numpy as np

#### Crear un array de 10 zeros 

In [4]:
np.arange(10) * 0 # xd

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

#### Crear un array de 10 ones

In [7]:
np.arange(10) * 0 + 1.0 # el ejemplo era float

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### Crear un array de 10 cincos

In [8]:
np.arange(10) * 0 + 5.

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

#### Crear un array de enteros desde 10 a 50

In [12]:
np.arange(10, 50 + 1) 

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

#### Cree una matriz de todos los enteros pares del 10 al 50

In [13]:
np.arange(10, 50 + 1, 2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

#### Cree una matriz de 3x3 con valores que van de 0 a 8

In [30]:
a = np.arange(9)
a = a.reshape(3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### Crear una matriz de identidad de 3x3

In [34]:
# np.eye(3)
a = np.arange(9) * 0.
a = a.reshape(3,3)
for i in range(a.shape[0]): # osea 3
    a[i,i] = 1.
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Use NumPy para generar un número aleatorio entre 0 y 1

In [15]:
np.random.rand(1)

array([0.70711807])

#### Utilice NumPy para generar una matriz de 25 números aleatorios muestreados a partir de una distribución normal estándar

In [47]:
np.random.randn(5,5) 

array([[-0.17614097, -0.77576244,  3.67354646, -0.15872609,  1.88813083],
       [ 1.16322043, -0.27720661,  0.2377887 ,  0.20220068,  0.42423971],
       [ 0.39030737, -0.26739354,  1.19918103,  0.82614294,  1.89406833],
       [ 0.47516073, -0.91081169, -0.09189072, -0.81952847, -1.2850328 ],
       [ 0.69951752, -0.14788383, -1.14823824,  0.65789652,  0.21750243]])

#### Cree la siguiente matriz:

In [45]:
#np.linspace(0,1, 100 + 1)
np.arange(101) / 100 

array([0.  , 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ,
       0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 , 0.21,
       0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 , 0.31, 0.32,
       0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 , 0.41, 0.42, 0.43,
       0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 , 0.51, 0.52, 0.53, 0.54,
       0.55, 0.56, 0.57, 0.58, 0.59, 0.6 , 0.61, 0.62, 0.63, 0.64, 0.65,
       0.66, 0.67, 0.68, 0.69, 0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76,
       0.77, 0.78, 0.79, 0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87,
       0.88, 0.89, 0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98,
       0.99, 1.  ])

#### Cree una matriz de 20 puntos espaciados linealmente entre 0 y 1:

In [54]:
# diablo que dificil me la pusite
#a = np.linspace(0,1,22) 
#a[1:-1]
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

## Numpy Indexación y Selección

Ahora se le darán algunas matrices y se le pedirá que replique los resultados de la matriz resultante:

In [55]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [64]:
# ESCRIBA AQUÍ EL CÓDIGO QUE REPRODUCE LA SALIDA DE LA CELDA A CONTINUACIÓN
# TENER CUIDADO DE NO HACER FUNCIONAR LA CELDA ABAJO, DE LO CONTRARIO NO
# PODRA VER LA SALIDA MÁS
mat[2:, 1:] #

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [76]:
# ESCRIBA AQUÍ EL CÓDIGO QUE REPRODUCE LA SALIDA DE LA CELDA A CONTINUACIÓN
# TENER CUIDADO DE NO HACER FUNCIONAR LA CELDA ABAJO, DE LO CONTRARIO NO
# PODRA VER LA SALIDA MÁS
mat[4-1, 5-1]

20

20

In [82]:
# ESCRIBA AQUÍ EL CÓDIGO QUE REPRODUCE LA SALIDA DE LA CELDA A CONTINUACIÓN
# TENER CUIDADO DE NO HACER FUNCIONAR LA CELDA ABAJO, DE LO CONTRARIO NO
# PODRA VER LA SALIDA MÁS
mat[:3,1].reshape(3,1)

array([[ 2],
       [ 7],
       [12]])

array([[ 2],
       [ 7],
       [12]])

In [83]:
# ESCRIBA AQUÍ EL CÓDIGO QUE REPRODUCE LA SALIDA DE LA CELDA A CONTINUACIÓN
# TENER CUIDADO DE NO HACER FUNCIONAR LA CELDA ABAJO, DE LO CONTRARIO NO
# PODRA VER LA SALIDA MÁS
mat[4]

array([21, 22, 23, 24, 25])

array([21, 22, 23, 24, 25])

In [84]:
# ESCRIBA AQUÍ EL CÓDIGO QUE REPRODUCE LA SALIDA DE LA CELDA A CONTINUACIÓN
# TENER CUIDADO DE NO HACER FUNCIONAR LA CELDA ABAJO, DE LO CONTRARIO NO
# PODRA VER LA SALIDA MÁS
mat[3:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

### Ahora hacer lo siguiente

#### Obtenga la suma de todos los valores en mat

In [93]:

if (np.sum(mat) == 25*(25+1)/2):
    print(np.sum(mat))
#325

325


#### Obtenga la desviación estándar de los valores en mat

In [102]:
#media
media = np.sum(mat)/mat.size
# cuadrado de distancia a la media
aux = (mat - media) ** 2
# sqrt(sumar valores de los cuadrados / num dato) 
aux = np.sqrt(np.sum(aux)/mat.size)
aux

7.211102550927978

7.2111025509279782

#### Obtenga la suma de todas las columnas en mat

In [94]:
s = 0
for col in mat:
    s += col
s

array([55, 60, 65, 70, 75])

array([55, 60, 65, 70, 75])

# Buen trabajo!